In [1]:
import pandas as pd
import numpy as np

In [2]:
#impressions_df_2022_q3 = pd.read_csv("./impressions_2022_q3.csv")
#impressions_df_2022_q4 = pd.read_csv("./impressions_2022_q4.csv")
#impressions_df_2023_q1 = pd.read_csv("./impressions_2023_q1.csv")

#impressions = pd.concat([impressions_df_2022_q3, impressions_df_2022_q4, impressions_df_2023_q1])
impressions = pd.read_csv("./impressions_2022_q3_q4_brands.csv")
impressions = impressions[impressions["gaze_valid"] == True]

In [3]:
impressions["true_is_iab_inview"] = impressions.apply(
    lambda x: 
    True if (
        (x["ad_technical_format"] == "out-stream") & (x["exist_viewable_1_s_threshold_50"] == True) & (x["exist_viewable_2_s_threshold_50"] == False)
    ) | (x["is_iab_inview"] == True) 
    else False, 
    axis=1
)

In [4]:
def get_size(x):
    return f"{x['ad_width_chosen']}x{x['ad_height_chosen']}"

impressions["size"] = impressions.apply(lambda x: get_size(x), axis=1)

In [5]:
from datetime import datetime
def get_day(x):
    date = datetime.strptime(x["first_event_at_iso"].split("T")[0], "%Y-%m-%d")
    return date.strftime("%A")

def get_week(x):
    date = datetime.strptime(x["first_event_at_iso"].split("T")[0], "%Y-%m-%d")
    return date.strftime("%V")

impressions["day"] = impressions.apply(lambda x: get_day(x), axis=1)
impressions["week"] = impressions.apply(lambda x: get_week(x), axis=1)

In [33]:
impressions["chosen_brand"].value_counts()

klarna        85112
amazon        37961
samsung       32506
elgiganten    26650
netonnet      16667
              ...
oppigards         1
stiga             1
garnier           1
bonaqua           1
bank24            1
Name: chosen_brand, Length: 394, dtype: int64

In [7]:
grouped_impressions = impressions.groupby(["part_year", "part_month", "hostname", "size", "chosen_brand"]).apply(
    lambda row: pd.Series(
        {
            "num_impressions": row["id"].count(),
            "num_fixations": row[row["is_fixated"] == True]["id"].count(),
            "total_fixation_duration": row["total_fixation_duration"].sum(),
            "num_inviews": row.loc[row["true_is_iab_inview"], "id"].count()
        }
    )
)
grouped_impressions = grouped_impressions.reset_index()
grouped_impressions

,part_year,part_month,hostname,size,chosen_brand,week,day,num_impressions,num_fixations,total_fixation_duration,num_inviews
0,2022,7,1001tracklists.com,468x240,leovegas,28,Friday,3,0,0,3
1,2022,7,180.se,180x150,polestar,27,Wednesday,3,0,0,0
2,2022,7,180.se,180x150,samsung,27,Wednesday,3,0,0,0
3,2022,7,180.se,728x90,cooptotal,27,Wednesday,1,0,0,0
4,2022,7,180.se,728x90,cooptotal,30,Wednesday,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
136857,2022,12,zkillboard.com,980x120,ford,51,Thursday,4,0,30,2
136858,2022,12,zkillboard.com,980x120,ford,52,Thursday,6,0,0,4
136859,2022,12,zkillboard.com,980x120,mmsports,52,Thursday,1,0,0,0
136860,2022,12,zkillboard.com,980x360,cooptotal,49,Saturday,1,0,0,0
136861,2022,12,zkillboard.com,980x360,snabbare,49,Saturday,1,0,58,1

In [8]:
facebook_imps = grouped_impressions[grouped_impressions["hostname"] == "facebook.com"]
facebook_imps["imp/fix_ratio"] = round(facebook_imps["num_fixations"] / facebook_imps["num_impressions"] * 100, 2)
facebook_imps.sort_values(by=["total_fixation_duration"], ascending=False)

,part_year,part_month,hostname,size,chosen_brand,week,day,num_impressions,num_fixations,total_fixation_duration,num_inviews
7501,2022,7,facebook.com,285x230,adlibris,27,Thursday,3,0,0,3
7502,2022,7,facebook.com,285x230,arket,28,Sunday,1,0,0,1
7503,2022,7,facebook.com,285x230,arvid,30,Sunday,2,0,0,2
7504,2022,7,facebook.com,285x230,asos,29,Wednesday,1,1,574,1
7505,2022,7,facebook.com,285x230,asos,30,Sunday,4,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...
118754,2022,12,facebook.com,500x555,wwf,51,Wednesday,10,8,462456,5
118755,2022,12,facebook.com,500x555,wwf,52,Friday,1,1,1096,0
118756,2022,12,facebook.com,500x555,wwf,52,Monday,4,4,382709,2
118757,2022,12,facebook.com,500x555,wwf,52,Saturday,2,2,1066,0
118758,2022,12,facebook.com,500x555,wwf,52,Tuesday,1,1,2522,1

In [13]:
# Topical ads generate the most fixation ratios, not the largest
# facebook_imps[facebook_imps["week"] == "49"].sort_values(by=["imp/fix_ratio"], ascending=False)

,part_year,part_month,hostname,size,chosen_brand,week,day,num_impressions,num_fixations,total_fixation_duration,num_inviews,imp/fix_ratio
118742,2022,12,facebook.com,500x555,wwf,49,Tuesday,1,1,1916,0,100.0
118686,2022,12,facebook.com,500x555,shein,49,Friday,2,2,1995,0,100.0
118675,2022,12,facebook.com,500x555,planinternational,49,Thursday,1,1,2106,1,100.0
118669,2022,12,facebook.com,500x555,moderaterna,49,Wednesday,1,1,22899,1,100.0
118668,2022,12,facebook.com,500x555,moderaterna,49,Tuesday,1,1,77405,1,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...
118199,2022,12,facebook.com,285x230,mediamarkt,49,Tuesday,2,0,0,2,0.0
118222,2022,12,facebook.com,285x230,mercedes,49,Monday,3,0,0,2,0.0
118223,2022,12,facebook.com,285x230,mercedes,49,Thursday,2,0,0,2,0.0
118245,2022,12,facebook.com,285x230,ncc,49,Thursday,1,0,0,1,0.0
118276,2022,12,facebook.com,285x230,nordicwellnes,49,Monday,1,0,0,1,0.0

In [14]:
# Generally speaking, sunday seems to have a bit more traction, but not high diff (single didget %)
# Day seems to vary a lot
aftonbladet_imps = grouped_impressions[grouped_impressions["hostname"] == "aftonbladet.se"]
#aftonbladet_imps["imp/fix_ratio"] = round(aftonbladet_imps["num_fixations"] / aftonbladet_imps["num_impressions"] * 100, 2)
#aftonbladet_imps = aftonbladet_imps[aftonbladet_imps["week"] == "49"]
aftonbladet_imps = aftonbladet_imps.groupby(["day"]).apply(
    lambda x: pd.Series(
        {
            "impressions": x["num_impressions"].sum(),
            "fixations": x["num_fixations"].sum(),
            "inviews": x["num_inviews"].sum(),
            "total_fixation_duration": x["total_fixation_duration"].sum()
        }
    )
)
aftonbladet_imps["imp/fix_ratio"] = round(aftonbladet_imps["fixations"] / aftonbladet_imps["impressions"] * 100, 2)
aftonbladet_imps.sort_values(by=["imp/fix_ratio"], ascending=False)

,impressions,fixations,inviews,total_fixation_duration,imp/fix_ratio
day,,,,,
Wednesday,772,180,346,377147,23.32
Sunday,517,117,267,130300,22.63
Monday,373,80,162,201722,21.45
Tuesday,791,166,376,339962,20.99
Friday,851,163,417,236104,19.15
Thursday,681,130,285,146700,19.09
Saturday,362,63,205,314592,17.40

In [43]:
prisjakt_imps = grouped_impressions[grouped_impressions["hostname"] == "prisjakt.nu"]
#prisjakt_imps
prisjakt_imps["imp/fix_ratio"] = round(prisjakt_imps["num_fixations"] / prisjakt_imps["num_impressions"] * 100, 2)
prisjakt_imps.sort_values(by=["imp/fix_ratio"], ascending=False)

/tmp/ipykernel_26143/1510168053.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  prisjakt_imps["imp/fix_ratio"] = round(prisjakt_imps["num_fixations"] / prisjakt_imps["num_impressions"] * 100, 2)

,part_year,part_month,hostname,size,chosen_brand,week,day,num_impressions,num_fixations,total_fixation_duration,num_inviews,imp/fix_ratio
17067,2022,7,prisjakt.nu,1180x240,netonnet,27,Sunday,1,1,966,1,100.0
70814,2022,9,prisjakt.nu,250x480,skoda,39,Monday,1,1,134,1,100.0
70802,2022,9,prisjakt.nu,250x480,mediamarkt,36,Friday,1,1,100,1,100.0
70800,2022,9,prisjakt.nu,250x480,honda,39,Monday,1,1,134,1,100.0
70795,2022,9,prisjakt.nu,250x480,audi,39,Monday,1,1,134,1,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...
70673,2022,9,prisjakt.nu,180x150,elgiganten,39,Thursday,10,0,0,0,0.0
70674,2022,9,prisjakt.nu,180x150,elgiganten,39,Tuesday,7,0,0,0,0.0
70675,2022,9,prisjakt.nu,180x150,elgiganten,39,Wednesday,6,0,0,0,0.0
70676,2022,9,prisjakt.nu,180x150,folksam,37,Wednesday,1,0,0,0,0.0
99727,2022,11,prisjakt.nu,160x600,hallon,45,Wednesday,10,0,0,4,0.0

In [28]:
telia_imps = grouped_impressions[grouped_impressions["chosen_brand"] == "telia"]
telia_imps["imp/fix_ratio"] = round(telia_imps["num_fixations"] / telia_imps["num_impressions"] * 100, 2)

tele2_imps = grouped_impressions[grouped_impressions["chosen_brand"] == "tele2"]
tele2_imps["imp/fix_ratio"] = round(tele2_imps["num_fixations"] / tele2_imps["num_impressions"] * 100, 2)

volvo_imps = grouped_impressions[grouped_impressions["chosen_brand"] == "volvo"]
volvo_imps["imp/fix_ratio"] = round(volvo_imps["num_fixations"] / volvo_imps["num_impressions"] * 100, 2)

mercedes_imps = grouped_impressions[grouped_impressions["chosen_brand"] == "mercedes"]
mercedes_imps["imp/fix_ratio"] = round(mercedes_imps["num_fixations"] / mercedes_imps["num_impressions"] * 100, 2)

ford_imps = grouped_impressions[grouped_impressions["chosen_brand"] == "ford"]
ford_imps["imp/fix_ratio"] = round(ford_imps["num_fixations"] / ford_imps["num_impressions"] * 100, 2)

elgiganten_imps = grouped_impressions[grouped_impressions["chosen_brand"] == "elgiganten"]
elgiganten_imps["imp/fix_ratio"] = round(elgiganten_imps["num_fixations"] / elgiganten_imps["num_impressions"] * 100, 2)

samsung_imps = grouped_impressions[grouped_impressions["chosen_brand"] == "samsung"]
samsung_imps["imp/fix_ratio"] = round(samsung_imps["num_fixations"] / samsung_imps["num_impressions"] * 100, 2)

/tmp/ipykernel_26143/4005354330.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  telia_imps["imp/fix_ratio"] = round(telia_imps["num_fixations"] / telia_imps["num_impressions"] * 100, 2)
/tmp/ipykernel_26143/4005354330.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tele2_imps["imp/fix_ratio"] = round(tele2_imps["num_fixations"] / tele2_imps["num_impressions"] * 100, 2)
/tmp/ipykernel_26143/4005354330.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  volvo_imps["imp/fix_ratio"] = round(volvo_imps["num_fixations"] / volvo_imps["num_impressions"] * 100, 2)
/tmp/ipykernel_26143/4005354330.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mercedes_imps["imp/fix_ratio"] = round(mercedes_imps["num_fixations"] / mercedes_imps["num_impressions"] * 100, 2)
/tmp/ipykernel_26143/4005354330.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ford_imps["imp/fix_ratio"] = round(ford_imps["num_fixations"] / ford_imps["num_impressions"] * 100, 2)
/tmp/ipykernel_26143/4005354330.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  elgiganten_imps["imp/fix_ratio"] = round(elgiganten_imps["num_fixations"] / elgiganten_imps["num_impressions"] * 100, 2)
/tmp/ipykernel_26143/4005354330.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  samsung_imps["imp/fix_ratio"] = round(samsung_imps["num_fixations"] / samsung_imps["num_impressions"] * 100, 2)

In [27]:
# Wider ads generate highest fixation ratio on news sites
telia_imps[telia_imps["num_impressions"] > 50].sort_values(by=["imp/fix_ratio"], ascending=False)

,part_year,part_month,hostname,size,chosen_brand,week,day,num_impressions,num_fixations,total_fixation_duration,num_inviews,imp/fix_ratio
19576,2022,7,telia.se,180x150,telia,27,Sunday,53,0,0,0,0.0
73432,2022,9,telia.se,180x150,telia,35,Saturday,68,0,0,0,0.0

In [26]:
# Wider ads generate highest fixation ratio on news sites
tele2_imps[tele2_imps["num_impressions"] > 50].sort_values(by=["imp/fix_ratio"], ascending=False)

Empty DataFrame
Columns: [part_year, part_month, hostname, size, chosen_brand, week, day, num_impressions, num_fixations, total_fixation_duration, num_inviews, imp/fix_ratio]
Index: []

In [23]:
volvo_imps[volvo_imps["num_impressions"] > 50].sort_values(by=["imp/fix_ratio"], ascending=False)

,part_year,part_month,hostname,size,chosen_brand,week,day,num_impressions,num_fixations,total_fixation_duration,num_inviews,imp/fix_ratio
44803,2022,8,tradera.com,980x240,volvo,32,Thursday,102,0,0,32,0.0
76731,2022,9,youtube.com,180x150,volvo,36,Friday,117,0,0,0,0.0
76735,2022,9,youtube.com,180x150,volvo,36,Thursday,169,0,0,0,0.0
76740,2022,9,youtube.com,180x150,volvo,37,Saturday,101,0,0,0,0.0
76741,2022,9,youtube.com,180x150,volvo,37,Sunday,125,0,0,0,0.0
76742,2022,9,youtube.com,180x150,volvo,37,Thursday,123,0,0,0,0.0
76743,2022,9,youtube.com,180x150,volvo,37,Tuesday,114,0,0,0,0.0
113544,2022,12,blocket.se,180x150,volvo,48,Friday,109,0,0,0,0.0

In [24]:
mercedes_imps[mercedes_imps["num_impressions"] > 50].sort_values(by=["imp/fix_ratio"], ascending=False)

,part_year,part_month,hostname,size,chosen_brand,week,day,num_impressions,num_fixations,total_fixation_duration,num_inviews,imp/fix_ratio
117791,2022,12,fabcrunch.com,300x250,mercedes,50,Monday,53,13,4724,25,24.53
131570,2022,12,thefashionball.com,300x250,mercedes,48,Saturday,73,13,3723,50,17.81
83735,2022,11,blocket.se,180x150,mercedes,46,Friday,110,0,0,0,0.00
113426,2022,12,blocket.se,180x150,mercedes,51,Monday,248,0,0,0,0.00

In [31]:
ford_imps[ford_imps["num_impressions"] > 50].sort_values(by=["imp/fix_ratio"], ascending=False)

,part_year,part_month,hostname,size,chosen_brand,week,day,num_impressions,num_fixations,total_fixation_duration,num_inviews,imp/fix_ratio
111215,2022,12,aftonbladet.se,468x240,ford,49,Wednesday,72,48,78343,45,66.67
81536,2022,11,aftonbladet.se,468x240,ford,46,Wednesday,108,55,60208,75,50.93
51615,2022,9,aftonbladet.se,468x240,ford,37,Thursday,69,23,44747,59,33.33
91085,2022,11,google.com,468x240,ford,47,Thursday,101,25,5524,57,24.75
81534,2022,11,aftonbladet.se,468x240,ford,46,Thursday,72,15,18342,55,20.83
51616,2022,9,aftonbladet.se,468x240,ford,37,Tuesday,69,11,2090,55,15.94
51625,2022,9,aftonbladet.se,468x240,ford,39,Thursday,72,11,2321,44,15.28
98807,2022,11,omni.se,980x240,ford,46,Friday,72,11,2277,50,15.28
136775,2022,12,zkillboard.com,160x600,ford,48,Sunday,56,5,1373,55,8.93
81532,2022,11,aftonbladet.se,468x240,ford,46,Monday,96,8,22640,36,8.33
98810,2022,11,omni.se,980x240,ford,46,Tuesday,60,1,742,46,1.67
44665,2022,8,tradera.com,980x240,ford,32,Thursday,83,0,0,53,0.00
74499,2022,9,tv.nu,160x600,ford,36,Wednesday,74,0,0,64,0.00
83639,2022,11,blocket.se,180x150,ford,47,Tuesday,147,0,0,0,0.00
114861,2022,12,comick.app,980x240,ford,52,Tuesday,100,0,0,10,0.00

In [34]:
elgiganten_imps[elgiganten_imps["num_impressions"] > 50].sort_values(by=["imp/fix_ratio"], ascending=False)

,part_year,part_month,hostname,size,chosen_brand,week,day,num_impressions,num_fixations,total_fixation_duration,num_inviews,imp/fix_ratio
91844,2022,11,google.com,468x480,elgiganten,47,Monday,75,49,117675,63,65.33
121335,2022,12,google.com,468x480,elgiganten,52,Tuesday,58,32,131257,44,55.17
91849,2022,11,google.com,468x480,elgiganten,47,Wednesday,123,66,232446,88,53.66
121334,2022,12,google.com,468x480,elgiganten,52,Thursday,56,28,64273,47,50.00
91843,2022,11,google.com,468x480,elgiganten,47,Friday,115,56,141573,79,48.70
91845,2022,11,google.com,468x480,elgiganten,47,Saturday,77,36,89592,54,46.75
91826,2022,11,google.com,468x480,elgiganten,44,Thursday,51,22,83349,35,43.14
128871,2022,12,prisjakt.nu,980x120,elgiganten,49,Tuesday,73,31,77139,56,42.47
121325,2022,12,google.com,468x480,elgiganten,51,Monday,55,23,60415,33,41.82
91839,2022,11,google.com,468x480,elgiganten,46,Sunday,59,24,369827,36,40.68
91846,2022,11,google.com,468x480,elgiganten,47,Sunday,86,31,144178,58,36.05
91052,2022,11,google.com,468x240,elgiganten,47,Friday,62,22,13376,37,35.48
91847,2022,11,google.com,468x480,elgiganten,47,Thursday,84,27,346716,40,32.14
34090,2022,8,google.com,125x230,elgiganten,32,Sunday,67,15,7317,30,22.39
91850,2022,11,google.com,468x480,elgiganten,48,Monday,84,17,42410,20,20.24
100440,2022,11,prisjakt.nu,980x120,elgiganten,47,Friday,71,14,10038,46,19.72
100427,2022,11,prisjakt.nu,980x120,elgiganten,45,Monday,96,18,10107,81,18.75
130686,2022,12,sweclockers.com,160x600,elgiganten,50,Friday,57,10,13404,50,17.54
9646,2022,7,google.com,125x230,elgiganten,27,Thursday,82,10,6078,18,12.20
9662,2022,7,google.com,125x230,elgiganten,29,Wednesday,92,11,6161,19,11.96
61455,2022,9,google.com,125x230,elgiganten,36,Saturday,55,6,6005,15,10.91
9655,2022,7,google.com,125x230,elgiganten,28,Wednesday,113,12,17185,28,10.62
34099,2022,8,google.com,125x230,elgiganten,33,Tuesday,125,12,11720,28,9.60
9649,2022,7,google.com,125x230,elgiganten,28,Friday,84,8,9440,33,9.52
34105,2022,8,google.com,125x230,elgiganten,34,Thursday,57,5,4881,10,8.77
88459,2022,11,facebook.com,285x230,elgiganten,47,Monday,55,4,5314,46,7.27
61459,2022,9,google.com,125x230,elgiganten,36,Wednesday,57,4,982,25,7.02
9644,2022,7,google.com,125x230,elgiganten,27,Saturday,105,7,6436,20,6.67
9656,2022,7,google.com,125x230,elgiganten,29,Friday,51,3,817,10,5.88
34095,2022,8,google.com,125x230,elgiganten,33,Monday,84,4,5273,19,4.76
9664,2022,7,google.com,125x230,elgiganten,30,Monday,53,2,1283,9,3.77
34096,2022,8,google.com,125x230,elgiganten,33,Saturday,53,2,3074,12,3.77
102520,2022,11,sweclockers.com,250x360,elgiganten,46,Saturday,70,2,467,19,2.86
114708,2022,12,chess.com,160x600,elgiganten,49,Sunday,51,1,153,45,1.96
9643,2022,7,google.com,125x230,elgiganten,27,Monday,63,1,336,15,1.59
100000,2022,11,prisjakt.nu,180x150,elgiganten,45,Monday,99,0,0,0,0.00
100013,2022,11,prisjakt.nu,180x150,elgiganten,47,Friday,65,0,0,0,0.00
114707,2022,12,chess.com,160x600,elgiganten,49,Saturday,80,0,0,80,0.00
114712,2022,12,chess.com,160x600,elgiganten,50,Monday,68,0,0,61,0.00
41824,2022,8,prisjakt.nu,180x150,elgiganten,31,Thursday,59,0,0,0,0.00
122990,2022,12,google.se,180x150,elgiganten,52,Tuesday,60,0,0,0,0.00
126911,2022,12,nwdb.info,160x600,elgiganten,52,Wednesday,56,0,0,56,0.00

In [20]:
samsung_imps[samsung_imps["num_impressions"] > 100].sort_values(by=["imp/fix_ratio"], ascending=False)

,part_year,part_month,hostname,size,chosen_brand,week,day,num_impressions,num_fixations,total_fixation_duration,num_inviews,imp/fix_ratio
120925,2022,12,google.com,468x240,samsung,52,Wednesday,104,48,395374,51,46.15
63417,2022,9,google.com,468x480,samsung,37,Sunday,120,52,2211032,56,43.33
121830,2022,12,google.com,468x480,samsung,48,Sunday,192,49,386747,65,25.52
120923,2022,12,google.com,468x240,samsung,52,Thursday,116,20,17272,79,17.24
61664,2022,9,google.com,125x230,samsung,36,Saturday,369,28,46330,45,7.59
34557,2022,8,google.com,125x230,samsung,33,Monday,140,0,0,0,0.00