In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load Q4 impressions
impressions_df = pd.read_csv("../datasets/impressions_q4_extended.csv")
impressions_df.head()

In [3]:
# Load schibsted report
schibsted_df = pd.read_excel("../datasets/report - 2023-02-01T152103.748 (1).xlsx")
schibsted_df

,Placement Id,Placement Name,Imps,Viewability Measurement Rate %,Viewability Rate % Xandr,Viewability Rate % Tobii
0,19499407,SE-Aftonbladet-wde-Article-Insider_1,154569684,0.903286,0.796216,60.03
1,19499410,SE-Aftonbladet-wde-Article-Modul_1,225338815,0.807402,0.818025,53.56
2,19499417,SE-Aftonbladet-wde-Article-Widescreen_1,230624683,0.948665,0.844853,62.30
3,19499420,SE-Aftonbladet-wde-Front-Insider_1,150265521,0.953058,0.655609,44.43
4,19499425,SE-Aftonbladet-wde-Front-Insider_6,50665822,0.947301,0.746351,43.52
5,19499428,SE-Aftonbladet-wde-Front-Modul_1,164006786,0.979427,0.654231,34.05
6,19499429,SE-Aftonbladet-wde-Front-Modul_10,15871065,0.864643,0.768467,42.54
7,19499430,SE-Aftonbladet-wde-Front-Modul_11,14093511,0.874710,0.789005,48.45
8,19499433,SE-Aftonbladet-wde-Front-Modul_4,54797161,0.884013,0.764235,49.24
9,19499437,SE-Aftonbladet-wde-Front-Modul_8,20403754,0.868936,0.784631,47.93
10,19499438,SE-Aftonbladet-wde-Front-Modul_9,18300225,0.952354,0.794724,48.74
11,19499440,SE-Aftonbladet-wde-Front-Takeover,71867383,0.627877,0.864007,69.94
12,19499441,SE-Aftonbladet-wde-Front-Toppanorama,188628599,0.982705,0.776880,62.44
13,19499442,SE-Aftonbladet-wde-Front-Widescreen_1,160026580,0.958060,0.855316,79.32
14,19499443,SE-Aftonbladet-wde-Front-Widescreen_2,162033777,0.981360,0.657494,39.30
15,19499449,SE-Aftonbladet-wde-Local-Widescreen_1,279572,0.956065,0.490570,55.26
16,19499470,SE-Aftonbladet-wph-Article-Toppanorama,369628770,0.968055,0.447466,57.72
17,19499475,SE-Aftonbladet-wph-Front-Panorama_1,265614960,0.980881,0.697766,42.86
18,19499490,SE-Aftonbladet-wph-Front-Toppanorama,340696332,0.969601,0.627201,69.31
19,19499521,SE-Blocket-wde-Object-Panorama_1,89094271,0.987521,0.671078,40.90
20,19499522,SE-Blocket-wde-Object-Post_it_1,91902346,0.793627,0.915530,34.43
21,19499523,SE-Blocket-wde-Object-Post_it_2,91905019,0.424492,0.619528,16.31
22,19499524,SE-Blocket-wde-Object-Post_it_3,91904535,0.311158,0.582755,14.13
23,19499532,SE-Blocket-wde-Result-Toppanorama,153281421,0.953573,0.625764,45.30
24,19499533,SE-Blocket-wde-Result-Widescreen_1,153891972,0.966034,0.794077,49.50
25,19499535,SE-Blocket-wde-Section-Panorama_1,1451744,0.988424,0.668833,32.18
26,19499541,SE-Blocket-wde-Section-Widescreen_1,1839347,0.967118,0.736978,38.33
27,19499542,SE-Blocket-wph-Front-Panorama_1,22593719,0.873698,0.659473,28.57
28,19499549,SE-Blocket-wph-Result-Panorama_1,114192323,0.968030,0.594317,43.48
29,19499550,SE-Blocket-wph-Result-Panorama_2,127479624,0.972200,0.670478,16.67
30,21067128,SE-Aftonbladet-wde-Front-Modul_12,12868636,0.956888,0.797987,48.65
31,21067129,SE-Aftonbladet-wde-Front-Modul_13,10915972,0.875360,0.794438,54.74
32,21067130,SE-Aftonbladet-wde-Front-Modul_14,10096662,0.869270,0.793156,52.07
33,21067133,SE-Aftonbladet-wde-Front-Modul_15,9490032,0.964184,0.810274,48.68
34,21067134,SE-Aftonbladet-wde-Front-Modul_16,8500751,0.872810,0.815311,46.72
35,23373659,SE-Aftonbladet-wde-Front-Modul_Backfill_1,153436800,0.025907,0.763301,32.97
36,23373681,SE-Aftonbladet-wde-Front-Modul_Backfill_3,17177528,0.954918,0.764544,44.90
37,23373701,SE-Aftonbladet-wde-Article-Modul_Backfill_1,2240379,0.742448,0.692508,34.21
38,23375557,SE-Aftonbladet-wde-Front-Modul_Backfill_4,21885373,0.957422,0.800098,52.10

In [4]:
import json

def extract_pid(placement_id):
    placement_id = json.loads(placement_id)
    bam_ad_slots = placement_id["bam_ad_slot"]
    # print(bam_ad_slots)
    final_bam_ad_slots = [bas for bas in bam_ad_slots if bas.strip() != '']
    ret = ''
    try:
        ret = placement_id['tag_id'][0]
    except:
        # print('.')
        ret = ','.join([bas for bas in final_bam_ad_slots])
    else:
        ret += ','.join([bas for bas in final_bam_ad_slots])
    return ret
    

def len_pids(placement_id):
    placement_id = json.loads(placement_id)
    bam_ad_slots = placement_id["bam_ad_slot"]
    final_bam_ad_slots = [bas for bas in bam_ad_slots if bas.strip() != '']
    return len(placement_id["tag_id"]) + len(final_bam_ad_slots)

def pid_type(pid):
    try:
        int(pid)
        return 'int'
    except:
        return 'str'

impressions_df['pid'] = impressions_df['placement_ids'].apply(extract_pid)
impressions_df['pid_len'] = impressions_df['placement_ids'].apply(len_pids)
impressions_df['pid_type'] = impressions_df['pid'].apply(pid_type)

In [6]:
impressions_df = impressions_df[impressions_df["pid_type"] == 'int']
impressions_df['pid'] = impressions_df['pid'].apply(lambda pid: int(pid))
impressions_df

,id,hostname,installation_id,session_id,beacon_type_chosen,ad_technical_format,channel,chosen_brand,ad_width_chosen,ad_height_chosen,...,placement_ids,placement_ids_chosen,time_in_screen,scroll_speed,total_fixation_duration,part_year,part_month,pid,pid_len,pid_type
0,a4215a13-e0d3-4819-b026-3b04e61c2cf0,blocket.se,78561cf5-4d4e-413e-a3ef-85e616b6225f,028e9d3c-b6d9-417d-94a8-2d5e9fb12f44,ad/tagid-iframe-v1,display,display,NaN,250,480,...,"{""tag_id"":[""19499522""],""bam_ad_slot"":["""","""",""""]}",NaN,4034.294,639.0,0,2022,10,19499522,1,int
1,ce05a01a-128f-4d5e-8b1c-838e2680a2eb,aftonbladet.se,737b86fb-5db9-4d07-b5bd-5419676cb4d8,5d5a0dfd-e5d6-4b7f-ad42-fc4d3c0aa3a0,ad/doubleclick.net-ins-dcmads-v1,display,display,NaN,160,600,...,"{""tag_id"":[""19499417""],""bam_ad_slot"":["""","""",""""]}",NaN,22.781,0.0,0,2022,10,19499417,1,int
275,35b72970-1738-46f7-825b-37befe3c0565,aftonbladet.se,9f13ee3d-922b-45f3-99a8-bf3be09f57e8,9c979b9c-dcb0-4cf9-a059-dc9157e23c08,ad/doubleclick-img-link-google-v1,display,display,NaN,250,480,...,"{""tag_id"":[""19499421""],""bam_ad_slot"":["""","""",""""]}",NaN,6.001,1821.0,0,2022,10,19499421,1,int
276,26dfc4a5-a335-4625-ad1b-d2c827a51026,aftonbladet.se,9f13ee3d-922b-45f3-99a8-bf3be09f57e8,9c979b9c-dcb0-4cf9-a059-dc9157e23c08,ad/anxv,display,display,NaN,250,480,...,"{""tag_id"":[""19499421""],""bam_ad_slot"":["""","""",""""]}",NaN,2.255,535.0,0,2022,10,19499421,1,int
277,a9a46d54-8271-4ed6-abf0-f1d1913ece46,aftonbladet.se,9f13ee3d-922b-45f3-99a8-bf3be09f57e8,9c979b9c-dcb0-4cf9-a059-dc9157e23c08,ad/doubleclick-img-link-google-v1,display,display,NaN,250,480,...,"{""tag_id"":[""19499421""],""bam_ad_slot"":["""","""",""""]}",NaN,6.001,1821.0,0,2022,10,19499421,1,int
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5730254,538983cc-2850-4130-8bd5-b2cf94102578,aftonbladet.se,65ce1d83-f075-4b06-bfae-c2ca8215da63,2e2a0960-0bd4-4e25-ab68-e0fda6e8bf94,ad/tagid-iframe-v1,display,display,NaN,468,240,...,"{""tag_id"":[""19499428""],""bam_ad_slot"":["""","""",""""]}",NaN,0.000,0.0,0,2022,12,19499428,1,int
5730255,128f342a-a607-49da-9efe-f70f30dd6a96,aftonbladet.se,65ce1d83-f075-4b06-bfae-c2ca8215da63,2e2a0960-0bd4-4e25-ab68-e0fda6e8bf94,ad/tagid-iframe-v1,display,display,NaN,250,480,...,"{""tag_id"":[""19499421""],""bam_ad_slot"":["""","""",""""]}",NaN,0.147,1417.0,0,2022,12,19499421,1,int
5730256,c03f2ec0-14b2-425a-bd96-d755ecc313e7,aftonbladet.se,65ce1d83-f075-4b06-bfae-c2ca8215da63,2e2a0960-0bd4-4e25-ab68-e0fda6e8bf94,ad/tagid-iframe-v1,display,display,NaN,160,600,...,"{""tag_id"":[""19499442""],""bam_ad_slot"":["""","""",""""]}",NaN,0.242,0.0,0,2022,12,19499442,1,int
5730257,7702b0ef-0b0d-4e6f-bc96-3e9051655f82,aftonbladet.se,65ce1d83-f075-4b06-bfae-c2ca8215da63,2e2a0960-0bd4-4e25-ab68-e0fda6e8bf94,ad/anxv,display,display,NaN,250,480,...,"{""tag_id"":[""19499421""],""bam_ad_slot"":["""","""",""""]}",NaN,43985.334,1417.0,0,2022,12,19499421,1,int
5730258,05a0bc59-9c45-493d-b1d0-512164c20547,aftonbladet.se,65ce1d83-f075-4b06-bfae-c2ca8215da63,2e2a0960-0bd4-4e25-ab68-e0fda6e8bf94,ad/anxv,display,display,NaN,160,600,...,"{""tag_id"":[""19499442""],""bam_ad_slot"":["""","""",""""]}",NaN,0.241,0.0,0,2022,12,19499442,1,int

In [7]:
pids = list(schibsted_df["Placement Id"].unique())
# Filter impressions to just include PID's from report
ab_df = impressions_df[impressions_df["pid"].isin(pids)]
ab_df

,id,hostname,installation_id,session_id,beacon_type_chosen,ad_technical_format,channel,chosen_brand,ad_width_chosen,ad_height_chosen,...,placement_ids,placement_ids_chosen,time_in_screen,scroll_speed,total_fixation_duration,part_year,part_month,pid,pid_len,pid_type
0,a4215a13-e0d3-4819-b026-3b04e61c2cf0,blocket.se,78561cf5-4d4e-413e-a3ef-85e616b6225f,028e9d3c-b6d9-417d-94a8-2d5e9fb12f44,ad/tagid-iframe-v1,display,display,NaN,250,480,...,"{""tag_id"":[""19499522""],""bam_ad_slot"":["""","""",""""]}",NaN,4034.294,639.0,0,2022,10,19499522,1,int
1,ce05a01a-128f-4d5e-8b1c-838e2680a2eb,aftonbladet.se,737b86fb-5db9-4d07-b5bd-5419676cb4d8,5d5a0dfd-e5d6-4b7f-ad42-fc4d3c0aa3a0,ad/doubleclick.net-ins-dcmads-v1,display,display,NaN,160,600,...,"{""tag_id"":[""19499417""],""bam_ad_slot"":["""","""",""""]}",NaN,22.781,0.0,0,2022,10,19499417,1,int
278,591e28ee-692c-4921-9971-2baabefb42db,aftonbladet.se,9f13ee3d-922b-45f3-99a8-bf3be09f57e8,9c979b9c-dcb0-4cf9-a059-dc9157e23c08,ad/tagid-iframe-v1,display,display,elgiganten,160,600,...,"{""tag_id"":[""19499443""],""bam_ad_slot"":["""","""",""""]}",NaN,84.753,19220.0,0,2022,10,19499443,1,int
279,c306f3aa-5f52-438f-8fcf-7eaf1cb328b5,aftonbladet.se,9f13ee3d-922b-45f3-99a8-bf3be09f57e8,9c979b9c-dcb0-4cf9-a059-dc9157e23c08,ad/doubleclick-img-link-google-v1,display,display,volvo,160,600,...,"{""tag_id"":[""19499442""],""bam_ad_slot"":["""","""",""""]}",NaN,103.412,1554.0,0,2022,10,19499442,1,int
286,ef062354-2627-4b8e-a35e-9a9ed7a26ddb,aftonbladet.se,9f13ee3d-922b-45f3-99a8-bf3be09f57e8,9c979b9c-dcb0-4cf9-a059-dc9157e23c08,ad/adnxs.com-iframe-v3,display,display,NaN,468,240,...,"{""tag_id"":[""19499433""],""bam_ad_slot"":["""","""",""""]}",NaN,1.621,0.0,0,2022,10,19499433,1,int
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5730239,3f74ca8b-7eb1-4dd2-864d-12293ec9ae41,aftonbladet.se,8787f1dc-9634-434c-b661-97f7e06a4f38,525f665f-331f-4906-a322-61e869d8e94f,ad/anxv,display,display,NaN,250,480,...,"{""tag_id"":[""19499420""],""bam_ad_slot"":["""","""",""""]}",NaN,12.197,0.0,0,2022,12,19499420,1,int
5730253,e1e26f94-0b21-4034-b00d-d128de91ea96,aftonbladet.se,65ce1d83-f075-4b06-bfae-c2ca8215da63,2e2a0960-0bd4-4e25-ab68-e0fda6e8bf94,ad/tagid-iframe-v1,display,display,NaN,160,600,...,"{""tag_id"":[""19499443""],""bam_ad_slot"":["""","""",""""]}",NaN,0.153,0.0,0,2022,12,19499443,1,int
5730254,538983cc-2850-4130-8bd5-b2cf94102578,aftonbladet.se,65ce1d83-f075-4b06-bfae-c2ca8215da63,2e2a0960-0bd4-4e25-ab68-e0fda6e8bf94,ad/tagid-iframe-v1,display,display,NaN,468,240,...,"{""tag_id"":[""19499428""],""bam_ad_slot"":["""","""",""""]}",NaN,0.000,0.0,0,2022,12,19499428,1,int
5730256,c03f2ec0-14b2-425a-bd96-d755ecc313e7,aftonbladet.se,65ce1d83-f075-4b06-bfae-c2ca8215da63,2e2a0960-0bd4-4e25-ab68-e0fda6e8bf94,ad/tagid-iframe-v1,display,display,NaN,160,600,...,"{""tag_id"":[""19499442""],""bam_ad_slot"":["""","""",""""]}",NaN,0.242,0.0,0,2022,12,19499442,1,int
5730258,05a0bc59-9c45-493d-b1d0-512164c20547,aftonbladet.se,65ce1d83-f075-4b06-bfae-c2ca8215da63,2e2a0960-0bd4-4e25-ab68-e0fda6e8bf94,ad/anxv,display,display,NaN,160,600,...,"{""tag_id"":[""19499442""],""bam_ad_slot"":["""","""",""""]}",NaN,0.241,0.0,0,2022,12,19499442,1,int

In [8]:
# Filter impression set to only use expressen
# client = "expressen.se"
#client_df = impressions_df[impressions_df["hostname"] == client]
# Get bonnier impression data
clients = ["expressen.se", "dn.se", "svd.se"]
bonnier_df = impressions_df[impressions_df["hostname"].isin(clients)]
bonnier_df

,id,hostname,installation_id,session_id,beacon_type_chosen,ad_technical_format,channel,chosen_brand,ad_width_chosen,ad_height_chosen,...,placement_ids,placement_ids_chosen,time_in_screen,scroll_speed,total_fixation_duration,part_year,part_month,pid,pid_len,pid_type
309,d3c69ae0-b3ff-4b14-9978-1ba95ef73dfd,svd.se,7a97dfb0-fe43-4dae-9b60-4cedd3afce6e,40666010-e3fa-4385-8946-723a83cd7e3b,ad/svd.se-ad-space-v1,display,display,NaN,1180,240,...,"{""tag_id"":[""19499712""],""bam_ad_slot"":["""","""",""""]}",NaN,5.580,0.0,91,2022,10,19499712,1,int
310,443a1ecc-127a-44ae-aee6-d94558731a45,svd.se,7a97dfb0-fe43-4dae-9b60-4cedd3afce6e,40666010-e3fa-4385-8946-723a83cd7e3b,ad/svd.se-ad-space-v1,display,display,NaN,468,480,...,"{""tag_id"":[""19499702""],""bam_ad_slot"":["""","""",""""]}",NaN,0.556,0.0,0,2022,10,19499702,1,int
313,a4658443-419c-4de5-bd30-706ec8d50a09,svd.se,7a97dfb0-fe43-4dae-9b60-4cedd3afce6e,d3cd7fcd-fa96-49a2-b631-4924c8b5a1be,ad/svd.se-ad-space-v1,display,display,NaN,1180,240,...,"{""tag_id"":[""19499712""],""bam_ad_slot"":["""","""",""""]}",NaN,5.328,164.0,0,2022,10,19499712,1,int
323,9fb0ec27-0811-451a-94fa-d872ab89a61e,svd.se,7a97dfb0-fe43-4dae-9b60-4cedd3afce6e,0290f52e-35ba-48c3-a1c7-efdc56045771,ad/svd.se-ad-space-v1,display,display,NaN,1180,240,...,"{""tag_id"":[""19499712""],""bam_ad_slot"":["""","""",""""]}",NaN,2.867,24.0,121,2022,10,19499712,1,int
342,9e0edf99-7ec8-4e05-acb0-bff9e36f13a2,svd.se,7a97dfb0-fe43-4dae-9b60-4cedd3afce6e,77d8ed29-4a81-4023-8259-8e806eb3e7a7,ad/doubleclick-img-link-google-v1,display,display,NaN,1180,240,...,"{""tag_id"":[""19499712""],""bam_ad_slot"":["""","""",""""]}",NaN,1.119,90.0,0,2022,10,19499712,1,int
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5729812,5e9db302-b2ae-4662-a409-0ec65816e069,svd.se,24d5d5c1-b1b8-4e86-9ef5-a5755372588a,23471e50-18a9-4500-ba79-ab7b3893bbd2,ad/svd.se-ad-space-v1,display,display,NaN,250,480,...,"{""tag_id"":[""19499717""],""bam_ad_slot"":["""","""",""""]}",NaN,0.000,9237.0,0,2022,12,19499717,1,int
5730020,6be4d798-b80e-402a-842c-559060450f14,svd.se,24d5d5c1-b1b8-4e86-9ef5-a5755372588a,23471e50-18a9-4500-ba79-ab7b3893bbd2,ad/adnxs.com-iframe-v3,out-stream,out-stream,NaN,1180,240,...,"{""tag_id"":[""19499727""],""bam_ad_slot"":["""","""",""""]}",NaN,0.000,0.0,0,2022,12,19499727,1,int
5730057,68208f4b-ec43-4f56-bb65-f2372173422e,expressen.se,fbdffafe-d9f8-4a49-a4a7-3b154956073f,bc3a789d-6056-43ff-a5a2-d39e34701ab3,ad/doubleclick.net-a-pcs-click-img-v1,display,display,NaN,250,480,...,"{""tag_id"":[""20148637""],""bam_ad_slot"":["""","""",""""]}",NaN,0.000,0.0,0,2022,12,20148637,1,int
5730121,1086c4be-985d-42f1-b959-b9d94c556e39,svd.se,24d5d5c1-b1b8-4e86-9ef5-a5755372588a,23471e50-18a9-4500-ba79-ab7b3893bbd2,ad/svd.se-ad-space-v1,display,display,NaN,250,480,...,"{""tag_id"":[""19499718""],""bam_ad_slot"":["""","""",""""]}",NaN,0.000,17268.0,0,2022,12,19499718,1,int
5730183,960a6326-bd8d-40f9-a249-6cc0ecf5dd75,svd.se,24d5d5c1-b1b8-4e86-9ef5-a5755372588a,23471e50-18a9-4500-ba79-ab7b3893bbd2,ad/anxv,display,display,NaN,1180,240,...,"{""tag_id"":[""19499723""],""bam_ad_slot"":["""","""",""""]}",NaN,0.000,918.0,0,2022,12,19499723,1,int

In [9]:
client_df = pd.concat([bonnier_df, ab_df])
client_df

,id,hostname,installation_id,session_id,beacon_type_chosen,ad_technical_format,channel,chosen_brand,ad_width_chosen,ad_height_chosen,...,placement_ids,placement_ids_chosen,time_in_screen,scroll_speed,total_fixation_duration,part_year,part_month,pid,pid_len,pid_type
309,d3c69ae0-b3ff-4b14-9978-1ba95ef73dfd,svd.se,7a97dfb0-fe43-4dae-9b60-4cedd3afce6e,40666010-e3fa-4385-8946-723a83cd7e3b,ad/svd.se-ad-space-v1,display,display,NaN,1180,240,...,"{""tag_id"":[""19499712""],""bam_ad_slot"":["""","""",""""]}",NaN,5.580,0.0,91,2022,10,19499712,1,int
310,443a1ecc-127a-44ae-aee6-d94558731a45,svd.se,7a97dfb0-fe43-4dae-9b60-4cedd3afce6e,40666010-e3fa-4385-8946-723a83cd7e3b,ad/svd.se-ad-space-v1,display,display,NaN,468,480,...,"{""tag_id"":[""19499702""],""bam_ad_slot"":["""","""",""""]}",NaN,0.556,0.0,0,2022,10,19499702,1,int
313,a4658443-419c-4de5-bd30-706ec8d50a09,svd.se,7a97dfb0-fe43-4dae-9b60-4cedd3afce6e,d3cd7fcd-fa96-49a2-b631-4924c8b5a1be,ad/svd.se-ad-space-v1,display,display,NaN,1180,240,...,"{""tag_id"":[""19499712""],""bam_ad_slot"":["""","""",""""]}",NaN,5.328,164.0,0,2022,10,19499712,1,int
323,9fb0ec27-0811-451a-94fa-d872ab89a61e,svd.se,7a97dfb0-fe43-4dae-9b60-4cedd3afce6e,0290f52e-35ba-48c3-a1c7-efdc56045771,ad/svd.se-ad-space-v1,display,display,NaN,1180,240,...,"{""tag_id"":[""19499712""],""bam_ad_slot"":["""","""",""""]}",NaN,2.867,24.0,121,2022,10,19499712,1,int
342,9e0edf99-7ec8-4e05-acb0-bff9e36f13a2,svd.se,7a97dfb0-fe43-4dae-9b60-4cedd3afce6e,77d8ed29-4a81-4023-8259-8e806eb3e7a7,ad/doubleclick-img-link-google-v1,display,display,NaN,1180,240,...,"{""tag_id"":[""19499712""],""bam_ad_slot"":["""","""",""""]}",NaN,1.119,90.0,0,2022,10,19499712,1,int
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5730239,3f74ca8b-7eb1-4dd2-864d-12293ec9ae41,aftonbladet.se,8787f1dc-9634-434c-b661-97f7e06a4f38,525f665f-331f-4906-a322-61e869d8e94f,ad/anxv,display,display,NaN,250,480,...,"{""tag_id"":[""19499420""],""bam_ad_slot"":["""","""",""""]}",NaN,12.197,0.0,0,2022,12,19499420,1,int
5730253,e1e26f94-0b21-4034-b00d-d128de91ea96,aftonbladet.se,65ce1d83-f075-4b06-bfae-c2ca8215da63,2e2a0960-0bd4-4e25-ab68-e0fda6e8bf94,ad/tagid-iframe-v1,display,display,NaN,160,600,...,"{""tag_id"":[""19499443""],""bam_ad_slot"":["""","""",""""]}",NaN,0.153,0.0,0,2022,12,19499443,1,int
5730254,538983cc-2850-4130-8bd5-b2cf94102578,aftonbladet.se,65ce1d83-f075-4b06-bfae-c2ca8215da63,2e2a0960-0bd4-4e25-ab68-e0fda6e8bf94,ad/tagid-iframe-v1,display,display,NaN,468,240,...,"{""tag_id"":[""19499428""],""bam_ad_slot"":["""","""",""""]}",NaN,0.000,0.0,0,2022,12,19499428,1,int
5730256,c03f2ec0-14b2-425a-bd96-d755ecc313e7,aftonbladet.se,65ce1d83-f075-4b06-bfae-c2ca8215da63,2e2a0960-0bd4-4e25-ab68-e0fda6e8bf94,ad/tagid-iframe-v1,display,display,NaN,160,600,...,"{""tag_id"":[""19499442""],""bam_ad_slot"":["""","""",""""]}",NaN,0.242,0.0,0,2022,12,19499442,1,int
5730258,05a0bc59-9c45-493d-b1d0-512164c20547,aftonbladet.se,65ce1d83-f075-4b06-bfae-c2ca8215da63,2e2a0960-0bd4-4e25-ab68-e0fda6e8bf94,ad/anxv,display,display,NaN,160,600,...,"{""tag_id"":[""19499442""],""bam_ad_slot"":["""","""",""""]}",NaN,0.241,0.0,0,2022,12,19499442,1,int

In [10]:
client_df = client_df[client_df["pid_type"] == "int"]

In [11]:
client_df["hostname"].value_counts()

aftonbladet.se    276438
blocket.se         63507
svd.se             29800
expressen.se        4848
dn.se                998
Name: hostname, dtype: int64

In [12]:
grouped_df = client_df.groupby(["hostname", "pid"]).apply(
    lambda x: pd.Series(
        {
            "num_impressions": x["id"].count(),
            "is_iab_inview": x[x["is_iab_inview"] == True]["id"].count()
        }
    )
)
grouped_df = grouped_df.reset_index()
grouped_df

           hostname       pid  num_impressions  is_iab_inview
0    aftonbladet.se  19499407            21734          13047
1    aftonbladet.se  19499410            24396          13067
2    aftonbladet.se  19499417            43047          26818
3    aftonbladet.se  19499420            26611          11824
4    aftonbladet.se  19499425             5683           2473
..              ...       ...              ...            ...
137          svd.se  19499746               76             31
138          svd.se  19499749               35             14
139          svd.se  19499750              266            118
140          svd.se  27264940               16              5
141          svd.se  27264953              354            194

[142 rows x 4 columns]

In [13]:
grouped_df["tobii_viewability%"] = grouped_df.apply(lambda x: round(x["is_iab_inview"] / x["num_impressions"] * 100, 0), axis=1)
grouped_df

,hostname,pid,num_impressions,is_iab_inview,tobii_viewability%
0,aftonbladet.se,19499407,21734,13047,60.0
1,aftonbladet.se,19499410,24396,13067,54.0
2,aftonbladet.se,19499417,43047,26818,62.0
3,aftonbladet.se,19499420,26611,11824,44.0
4,aftonbladet.se,19499425,5683,2473,44.0
...,...,...,...,...,...
137,svd.se,19499746,76,31,41.0
138,svd.se,19499749,35,14,40.0
139,svd.se,19499750,266,118,44.0
140,svd.se,27264940,16,5,31.0
141,svd.se,27264953,354,194,55.0

In [14]:
grouped_df["hostname"].value_counts()

expressen.se      49
svd.se            38
aftonbladet.se    28
dn.se             18
blocket.se         9
Name: hostname, dtype: int64

In [16]:
average_df = grouped_df.groupby("hostname").apply(
    lambda x: pd.Series(
        {
            "average_tobii_viewability": np.average(x["tobii_viewability%"]),
            "num_of_placements": x["pid"].count(),
            "num_of_impressions": np.sum(x["num_impressions"])
        }
    )
)
average_df = average_df.reset_index()
average_df

,hostname,average_tobii_viewability,num_of_placements,num_of_impressions
0,aftonbladet.se,50.928571,28.0,276438.0
1,blocket.se,31.111111,9.0,63507.0
2,dn.se,62.333333,18.0,998.0
3,expressen.se,54.367347,49.0,4848.0
4,svd.se,52.578947,38.0,29800.0

In [17]:
average_df.to_excel("../final_reports/ATEX2-965_average_stats.xlsx")
average_df.to_csv("../final_reports/ATEX2-965_average_stats.csv")

grouped_df.to_excel("../final_reports/ATEX2-965_tobii_viewability_comparison.xlsx")
grouped_df.to_csv("../final_reports/ATEX2-965_tobii_viewability_comparison.csv")
print("done")

done