In [1]:
import pandas as pd
import numpy as np

In [4]:
# load impressions for 2022
impressions_df = pd.read_csv('../datasets/impressions_10_11_12.csv')
impressions_df

,id,hostname,installation_id,session_id,beacon_type_chosen,ad_technical_format,channel,chosen_brand,ad_width_chosen,ad_height_chosen,...,demographic,month_iso,first_event_at_iso,placement_ids,placement_ids_chosen,time_in_screen,scroll_speed,total_fixation_duration,part_year,part_month
0,c3c492e5-19b5-4d47-b6d9-da7f918653ab,hgaapnaapbegifeilocnkmciphfggffm,440763c4-ae4a-45a0-ad3a-786c7a9725ee,63919154-c54f-4e82-803d-925dd8bce0d1,vnd/hgaapnaapbegifeilocnkmciphfggffm,display,display,NaN,250,120,...,"{""country"":"""",""gender"":"""",""age"":""""}",2022-10,2022-10-20T08:12:20.952Z,"{""tag_id"":[],""bam_ad_slot"":["""","""",""""]}",NaN,0.000,0.0,0,2022,10
1,ddb89754-22ff-4e0e-a914-9da4d722d92d,youtube.com,d268ef26-5b9f-4be1-8e68-665aa6abfaf2,099f1d90-53e3-4366-bfd4-033fa24658cd,ad/youtube.com-home-feed-v1,display,display,NaN,300,250,...,"{""country"":""Sweden"",""gender"":""Male"",""age"":""24""}",2022-10,2022-10-04T10:52:48.186Z,"{""tag_id"":[],""bam_ad_slot"":["""","""",""""]}",NaN,40.806,253.0,45,2022,10
2,f8a4defe-0b4a-4779-a082-4b3df612dd4b,youtube.com,d268ef26-5b9f-4be1-8e68-665aa6abfaf2,099f1d90-53e3-4366-bfd4-033fa24658cd,ad/youtube.com-home-feed-v1,display,display,NaN,300,250,...,"{""country"":""Sweden"",""gender"":""Male"",""age"":""24""}",2022-10,2022-10-04T10:55:20.771Z,"{""tag_id"":[],""bam_ad_slot"":["""","""",""""]}",NaN,0.923,0.0,0,2022,10
3,f91b8c39-94bf-4fb3-b0d3-fbbf9212a242,apps.facebook.com,122a6d00-f566-4c80-8342-ba1a4bfb1c02,3a247179-591e-4abb-a6d0-c521bc7b72cf,ad/doubleclick.net-a-pcs-click-img-v1,display,social,NaN,728,90,...,"{""country"":""Sweden"",""gender"":""Female"",""age"":""60""}",2022-10,2022-10-25T04:01:06.493Z,"{""tag_id"":[],""bam_ad_slot"":["""","""",""""]}",NaN,0.000,0.0,0,2022,10
4,aef6cf14-abd7-4708-9167-78851b27ff57,apps.facebook.com,122a6d00-f566-4c80-8342-ba1a4bfb1c02,3a247179-591e-4abb-a6d0-c521bc7b72cf,ad/doubleclick.net-a-pcs-click-img-v1,display,social,NaN,728,90,...,"{""country"":""Sweden"",""gender"":""Female"",""age"":""60""}",2022-10,2022-10-25T04:03:06.507Z,"{""tag_id"":[],""bam_ad_slot"":["""","""",""""]}",NaN,0.000,0.0,0,2022,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5730215,e4284ddf-0741-4532-a317-408e879ec6d4,allabolag.se,4d069e8d-c77d-4705-a333-fd6ab73aef20,63aec6aa-d214-4cdc-b9ae-a65627c5637b,ad/leeads-v1,display,display,NaN,300,250,...,"{""country"":"""",""gender"":"""",""age"":""""}",2022-12,2022-12-30T10:51:17.047Z,"{""tag_id"":[""allabolag_desktop-left2_3""],""bam_a...",NaN,26.999,564.0,0,2022,12
5730216,07f6e1c6-f2b3-4ee2-b712-4823f27d2777,allabolag.se,4d069e8d-c77d-4705-a333-fd6ab73aef20,63aec6aa-d214-4cdc-b9ae-a65627c5637b,ad/leeads-v1,display,display,NaN,300,250,...,"{""country"":"""",""gender"":"""",""age"":""""}",2022-12,2022-12-30T10:51:17.047Z,"{""tag_id"":[""allabolag_desktop-left2_1""],""bam_a...",NaN,4.232,266.0,0,2022,12
5730217,102425cd-9fb2-4a2e-abfc-925b53d89f20,allabolag.se,4d069e8d-c77d-4705-a333-fd6ab73aef20,63aec6aa-d214-4cdc-b9ae-a65627c5637b,ad/leeads-v1,display,display,NaN,300,250,...,"{""country"":"""",""gender"":"""",""age"":""""}",2022-12,2022-12-30T10:51:17.047Z,"{""tag_id"":[""allabolag_desktop-left2_2""],""bam_a...",NaN,0.005,357.0,0,2022,12
5730218,914953f6-7e3d-467a-94cd-168c83adacf1,allabolag.se,4d069e8d-c77d-4705-a333-fd6ab73aef20,63aec6aa-d214-4cdc-b9ae-a65627c5637b,ad/leeads-v1,display,display,NaN,300,250,...,"{""country"":"""",""gender"":"""",""age"":""""}",2022-12,2022-12-30T10:51:17.047Z,"{""tag_id"":[""allabolag_desktop-left1""],""bam_ad_...",NaN,45.505,414.0,0,2022,12
5730219,7c12ade2-5954-4971-b95b-73bc390a45d6,youtube.com,603dcd90-7ec8-442f-b1b4-7f67476133f6,35a79a99-39a1-4a3f-b6a7-804c3dca6c05,ad/youtube.com-home-feed-v1,display,display,NaN,180,150,...,"{""country"":""Sweden"",""gender"":""Male"",""age"":""51""}",2022-12,2022-12-30T10:07:41.555Z,"{""tag_id"":[],""bam_ad_slot"":["""","""",""""]}",NaN,0.000,0.0,0,2022,12

In [3]:
import json

def extract_pid(placement_id):
    placement_id = json.loads(placement_id)
    print(placement_id)
    bam_ad_slots = placement_id["bam_ad_slot"]
    final_bam_ad_slots = [bas for bas in bam_ad_slots if bas.strip() != '']
    try:
        ret = placement_id['tag_id'][0]
    except:
        print('empty pid')
        return
    ret += ','.join([bas for bas in final_bam_ad_slots])
    return ret
    

def len_pids(placement_id):
    placement_id = json.loads(placement_id)
    bam_ad_slots = placement_id["bam_ad_slot"]
    final_bam_ad_slots = [bas for bas in bam_ad_slots if bas.strip() != '']
    return len(placement_id["tag_id"]) + len(final_bam_ad_slots)

def pid_type(pid):
    try:
        int(pid)
        return 'int'
    except:
        return 'str'

impressions_df['pid'] = impressions_df['placement_ids'].apply(extract_pid)
impressions_df['pid_len'] = impressions_df['placement_ids'].apply(len_pids)
impressions_df['pid_type'] = impressions_df['pid'].apply(pid_type)

KeyError: 'placement_ids'

In [65]:
impressions_df['pid_type'].value_counts()

str    5001359
int     728861
Name: pid_type, dtype: int64

In [66]:
# filter only impressions with int placement IDs
impressions_df = impressions_df[impressions_df['pid_type'] == 'int']
impressions_df.head()

,id,hostname,installation_id,session_id,beacon_type_chosen,ad_technical_format,channel,chosen_brand,ad_width_chosen,ad_height_chosen,...,placement_ids,placement_ids_chosen,time_in_screen,scroll_speed,total_fixation_duration,part_year,part_month,pid,pid_len,pid_type
41,4d3042e3-3081-41be-8965-9b45af9b9e31,aftonbladet.se,0e593f23-b901-4542-97c1-2025e22c0a36,0c1d9dba-e25f-4fd9-9ae5-293ba21f2426,ad/tagid-iframe-v1,display,display,NaN,980,240,...,"{""tag_id"":[""19499441""],""bam_ad_slot"":["""","""",""""]}",NaN,180012.209,228.0,0,2022,10,19499441,1,int
42,91b21f92-b192-4318-b3b8-5d4f44eb45f2,aftonbladet.se,0e593f23-b901-4542-97c1-2025e22c0a36,0c1d9dba-e25f-4fd9-9ae5-293ba21f2426,ad/tagid-iframe-v1,display,display,kfc,160,600,...,"{""tag_id"":[""19499442""],""bam_ad_slot"":["""","""",""""]}",NaN,9.641,249.0,0,2022,10,19499442,1,int
43,613057cf-6340-4ea1-9439-93a1891d661b,aftonbladet.se,0e593f23-b901-4542-97c1-2025e22c0a36,0c1d9dba-e25f-4fd9-9ae5-293ba21f2426,ad/anxv,display,display,hallon,160,600,...,"{""tag_id"":[""19499443""],""bam_ad_slot"":["""","""",""""]}",NaN,0.008,0.0,0,2022,10,19499443,1,int
44,cba3f5e7-8c22-42c2-987c-a5e230315664,aftonbladet.se,0e593f23-b901-4542-97c1-2025e22c0a36,0c1d9dba-e25f-4fd9-9ae5-293ba21f2426,ad/tagid-iframe-v1,display,display,hallon,160,600,...,"{""tag_id"":[""19499443""],""bam_ad_slot"":["""","""",""""]}",NaN,0.008,0.0,0,2022,10,19499443,1,int
45,b6aa6f3c-f4c9-4085-8c13-9022c0162ad9,aftonbladet.se,0e593f23-b901-4542-97c1-2025e22c0a36,0c1d9dba-e25f-4fd9-9ae5-293ba21f2426,ad/anxv,display,display,NaN,980,240,...,"{""tag_id"":[""19499441""],""bam_ad_slot"":["""","""",""""]}",NaN,180012.122,41.0,0,2022,10,19499441,1,int

In [67]:
# convert placement ids that can be converted to the int to be int, not string
# type(impressions_df.iloc[0]['pid'])     # check this, right now they're strings
impressions_df['pid'] = impressions_df['pid'].apply(lambda pid: int(pid))

/home/markopejic/clear/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [68]:
type(impressions_df.iloc[0]['pid'])

numpy.int64

In [69]:
# run through predictions
import os
import json


def _get_pred_map():
    pred_map = dict()
    
    for i in range(1, 13):
        if i < 10:
            i = f'0{i}'
        for day in os.listdir(f'../predictions/2022/{i}'):
            for h in os.listdir(f'../predictions/2022/{i}/{day}'):
                if not h.endswith('.ndjson'):
                    continue
                with open(f'../predictions/2022/{i}/{day}/{h}')as f:
                    for line in f.readlines():
                        json_line = json.loads(line)
                        id_ = json_line['id']
                        pred_map[id_] = json_line['prediction']
    return pred_map
                            
pred_map = _get_pred_map()

In [70]:
def _get_final_fixation(gaze_valid, is_fixated, id_, pred_map):
    if gaze_valid:
        return is_fixated
    if id_ in pred_map:
        return pred_map[id_]
    return False

impressions_df['final_fixation'] = impressions_df.apply(lambda row: _get_final_fixation(row['gaze_valid'], row['is_fixated'], row['id'], pred_map), axis=1)
impressions_df

/home/markopejic/clear/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,id,hostname,installation_id,session_id,beacon_type_chosen,ad_technical_format,channel,chosen_brand,ad_width_chosen,ad_height_chosen,...,placement_ids_chosen,time_in_screen,scroll_speed,total_fixation_duration,part_year,part_month,pid,pid_len,pid_type,final_fixation
41,4d3042e3-3081-41be-8965-9b45af9b9e31,aftonbladet.se,0e593f23-b901-4542-97c1-2025e22c0a36,0c1d9dba-e25f-4fd9-9ae5-293ba21f2426,ad/tagid-iframe-v1,display,display,NaN,980,240,...,NaN,180012.209,228.0,0,2022,10,19499441,1,int,True
42,91b21f92-b192-4318-b3b8-5d4f44eb45f2,aftonbladet.se,0e593f23-b901-4542-97c1-2025e22c0a36,0c1d9dba-e25f-4fd9-9ae5-293ba21f2426,ad/tagid-iframe-v1,display,display,kfc,160,600,...,NaN,9.641,249.0,0,2022,10,19499442,1,int,False
43,613057cf-6340-4ea1-9439-93a1891d661b,aftonbladet.se,0e593f23-b901-4542-97c1-2025e22c0a36,0c1d9dba-e25f-4fd9-9ae5-293ba21f2426,ad/anxv,display,display,hallon,160,600,...,NaN,0.008,0.0,0,2022,10,19499443,1,int,False
44,cba3f5e7-8c22-42c2-987c-a5e230315664,aftonbladet.se,0e593f23-b901-4542-97c1-2025e22c0a36,0c1d9dba-e25f-4fd9-9ae5-293ba21f2426,ad/tagid-iframe-v1,display,display,hallon,160,600,...,NaN,0.008,0.0,0,2022,10,19499443,1,int,False
45,b6aa6f3c-f4c9-4085-8c13-9022c0162ad9,aftonbladet.se,0e593f23-b901-4542-97c1-2025e22c0a36,0c1d9dba-e25f-4fd9-9ae5-293ba21f2426,ad/anxv,display,display,NaN,980,240,...,NaN,180012.122,41.0,0,2022,10,19499441,1,int,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5730208,c4d7a5fe-e2ee-42d4-8455-df50637c7699,aftonbladet.se,fb2854c1-265d-4ace-acd1-9d4418dfa289,2ab33511-a4e8-467d-b978-798a13252543,ad/adnxs.com-iframe-v3,display,display,NaN,160,600,...,NaN,43470.912,0.0,0,2022,12,19499443,1,int,False
5730209,f1596b42-5e22-42f7-9cc9-c9378e3e9fd4,aftonbladet.se,fb2854c1-265d-4ace-acd1-9d4418dfa289,2ab33511-a4e8-467d-b978-798a13252543,ad/doubleclick.net-ins-dcmads-v1,display,display,eon,980,240,...,NaN,22622.639,0.0,0,2022,12,19499441,1,int,True
5730210,a1a508de-32fb-4a84-af44-0648bf8066d7,aftonbladet.se,fb2854c1-265d-4ace-acd1-9d4418dfa289,2ab33511-a4e8-467d-b978-798a13252543,ad/doubleclick.net-ins-dcmads-v1,display,display,eon,980,240,...,NaN,22603.947,0.0,0,2022,12,19499441,1,int,True
5730211,e5835082-cba4-4bb2-888a-b9e85a6cdf64,aftonbladet.se,fb2854c1-265d-4ace-acd1-9d4418dfa289,2ab33511-a4e8-467d-b978-798a13252543,ad/adnxs.com-iframe-v3,display,display,NaN,250,480,...,NaN,20768.062,0.0,0,2022,12,19499420,1,int,False
5730212,fdf669ee-44af-4d9b-a6e7-3036b2c80f7b,aftonbladet.se,fb2854c1-265d-4ace-acd1-9d4418dfa289,2ab33511-a4e8-467d-b978-798a13252543,ad/adnxs.com-iframe-v3,display,display,NaN,160,600,...,NaN,43470.336,0.0,0,2022,12,19499442,1,int,False

In [169]:
# load tele2 dataset
df_client_tele2 = pd.read_csv('../datasets/bq-results-20221214-130759-1671023289214.csv')
df_client_tele2

,is_iab_inview,is_imp,iab_width,iab_height,placement_id,testgroup,gender,age,hostname,brand,ad_format,panel_id
0,0,1,980,600,19589659,control_group,uknown,0,golf.se,SE_MCM_TEL_TELE2,Display,4626177109561431157
1,0,1,320,320,18803692,control_group,uknown,0,mrkoll.se,SE_MCM_TEL_TELE2,Display,7371926167922483381
2,1,1,320,320,24893359,control_group,uknown,0,synonymer.se,SE_MCM_TEL_TELE2,Display,2501818363642076224
3,1,1,320,480,18803692,control_group,uknown,0,mrkoll.se,SE_MCM_TEL_TELE2,Display,7659201791647059694
4,0,1,320,320,26448108,control_group,uknown,0,eniro.se,SE_MCM_TEL_TELE2,Display,3591778167681202912
...,...,...,...,...,...,...,...,...,...,...,...,...
421786,1,1,320,320,27117564,control_group,uknown,0,kampanjveckan.se,SE_MCM_TEL_TELE2,Display,5139617438975557195
421787,1,1,320,320,27117564,control_group,uknown,0,kampanjveckan.se,SE_MCM_TEL_TELE2,Display,7748934308138043968
421788,1,1,320,320,27117564,control_group,uknown,0,kampanjveckan.se,SE_MCM_TEL_TELE2,Display,8009546458316678439
421789,1,1,320,320,27117564,control_group,uknown,0,kampanjveckan.se,SE_MCM_TEL_TELE2,Display,8152800463819604519
421790,1,1,320,320,27117564,control_group,uknown,0,kampanjveckan.se,SE_MCM_TEL_TELE2,Display,7641616160758278421

In [170]:
# filter only impressions
df_client_tele2 = df_client_tele2[df_client_tele2['is_imp'] == True]
df_client_tele2.shape

(421409, 12)

In [171]:
df_client_tele2['testgroup'].value_counts()

attention_group    210717
control_group      210692
Name: testgroup, dtype: int64

In [172]:
# filter specific campaign
campaign = 'control_group'
df_client_tele2 = df_client_tele2[df_client_tele2['testgroup'] == campaign]
print(df_client_tele2.shape)

(210692, 12)

In [173]:
# filter only impressions with tele2 placement IDs
tele2_placements = list(df_client_tele2['placement_id'].unique())
tele2_impressions = impressions_df[impressions_df['pid'].isin(tele2_placements)]
tele2_impressions

,id,hostname,installation_id,session_id,beacon_type_chosen,ad_technical_format,channel,chosen_brand,ad_width_chosen,ad_height_chosen,...,placement_ids_chosen,time_in_screen,scroll_speed,total_fixation_duration,part_year,part_month,pid,pid_len,pid_type,final_fixation
41859,14f36eb2-d6f4-4ce6-9598-7f6dc36bee0f,merinfo.se,ccbbc8a0-5b1d-4115-9bf0-7e02dcff8e37,0ea2ac14-095c-450a-b6a2-2b0b37b2b1cc,ad/doubleclick-img-link-google-v1,display,display,NaN,980,240,...,NaN,0.000,0.0,0,2022,10,24893255,1,int,False
41881,ac1320a7-8d93-4325-8aec-0d62d76d4741,merinfo.se,ccbbc8a0-5b1d-4115-9bf0-7e02dcff8e37,bc9f801b-59fa-461c-ade3-0a4c6faf6301,ad/doubleclick-img-link-google-v1,display,display,nordea,980,240,...,NaN,0.001,0.0,93,2022,10,24893255,1,int,True
41882,33e410a5-f772-4780-88ad-420428082bbb,merinfo.se,ccbbc8a0-5b1d-4115-9bf0-7e02dcff8e37,bc9f801b-59fa-461c-ade3-0a4c6faf6301,ad/anxv,display,display,NaN,180,150,...,NaN,0.000,0.0,0,2022,10,24893255,1,int,False
60510,b873e0e2-4b9d-4f14-9854-5b31e3eabb6d,tradera.com,5314c2cc-dc21-46de-a8d7-797328bfcb57,269fa453-e22e-4512-855f-529b213325f0,ad/trandera-banner-v1,out-stream,out-stream,NaN,980,360,...,NaN,0.000,711.0,0,2022,10,25415006,1,int,False
60569,4ec31d08-8199-4e44-ac88-656ffb2bb2b7,tradera.com,5314c2cc-dc21-46de-a8d7-797328bfcb57,2ca7eb1b-ed32-48e4-bd86-d5bbbbf762bf,ad/trandera-banner-v1,out-stream,out-stream,NaN,980,240,...,NaN,0.000,711.0,0,2022,10,25415005,1,int,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5708838,22149bad-5500-40c6-a506-855d3173a27d,tradera.com,5314c2cc-dc21-46de-a8d7-797328bfcb57,5bae674b-638a-4fdd-b520-f946933a7b60,ad/trandera-banner-v1,display,display,amazon,980,240,...,NaN,0.000,0.0,0,2022,12,25415005,1,int,False
5714507,61e8cd0f-3ae5-4db5-ac87-ba4f25028ad8,tradera.com,70c9551d-fdae-4326-b93f-386ee3d54270,8629f8d9-f1e2-4b63-a0a6-3c0f8ec47570,ad/adnxs.com-a-img-v1,display,display,NaN,980,240,...,NaN,0.001,0.0,0,2022,11,25415006,1,int,False
5714508,d59eb698-9636-4657-aa67-bc7ff9c2ea65,tradera.com,70c9551d-fdae-4326-b93f-386ee3d54270,8629f8d9-f1e2-4b63-a0a6-3c0f8ec47570,ad/doubleclick.net-a-pcs-click-img-v1,display,display,NaN,980,240,...,NaN,0.000,0.0,0,2022,11,25415006,1,int,False
5717051,16a9f182-ee9f-4cb8-878e-d1b2c83dd35f,tradera.com,1b7c9e28-3db0-428e-b9a6-8d757a8de324,b92b24bc-6b5a-4f3c-a044-dc728876d1eb,ad/anxv,display,display,NaN,180,150,...,NaN,0.000,0.0,0,2022,12,25415005,1,int,False
5724675,7f870aa4-9cf5-42d0-a738-286b1ea4333a,tradera.com,70c9551d-fdae-4326-b93f-386ee3d54270,8629f8d9-f1e2-4b63-a0a6-3c0f8ec47570,ad/anxv,display,display,NaN,180,150,...,NaN,0.000,0.0,0,2022,11,25415006,1,int,False

In [174]:
len(tele2_placements)

283

In [175]:
# groupby and aggregate
grouped_df = tele2_impressions.groupby(['hostname', 'pid']).apply(
    lambda x: pd.Series(
        {
            'num_impressions' : x['id'].count(),
            'num_fixations': x.loc[x['final_fixation'],'id'].count()
        }
    )
)

In [176]:
grouped_df['ratio'] = round(grouped_df['num_fixations'] / grouped_df['num_impressions'], 4)
grouped_df['ratio_percent'] = round(grouped_df['ratio'] * 100, 2)
grouped_df

                               num_impressions  num_fixations   ratio  \
hostname             pid
allas.se             27190878                1              0  0.0000
                     27190909                3              0  0.0000
elevspel.se          24893322                5              0  0.0000
                     24893323                3              0  0.0000
eliteprospects.com   14006303                1              0  0.0000
elle.se              27191265                1              0  0.0000
                     27191267                4              0  0.0000
                     27208167                3              0  0.0000
eniro.se             26447955                6              2  0.3333
                     26447956                6              2  0.3333
                     26448029                7              0  0.0000
                     26448041                2              1  0.5000
                     26448062               16              2  0.1250
                     26448063                4              0  0.0000
everysport.com       14006888                1              0  0.0000
feber.se             18805247                3              0  0.0000
                     18805253                3              0  0.0000
                     18805260                4              0  0.0000
                     18805261                5              0  0.0000
                     18805264                2              0  0.0000
                     18805300                3              0  0.0000
                     18805311                2              0  0.0000
femina.se            27208168                1              0  0.0000
fotbolldirekt.se     14006827                1              1  1.0000
                     18911735                1              0  0.0000
gp.se                19402974                4              0  0.0000
gulesider.no         24984881                1              0  0.0000
hant.se              27191378                1              0  0.0000
                     27191384                9              0  0.0000
hockeyallsvenskan.se 17556315                2              0  0.0000
kokaihop.se          24893273                1              0  0.0000
                     24893274                9              0  0.0000
land.se              24984948                6              0  0.0000
                     24985284                1              0  0.0000
mabra.com            27191428                1              0  0.0000
                     27191431                1              0  0.0000
merinfo.se           24893255               32              7  0.2188
                     24893256                6              3  0.5000
                     24893357               34              8  0.2353
                     24893358               46              4  0.0870
mingolf.golf.se      19589657                3              0  0.0000
mrkoll.se            18803686               32             16  0.5000
                     18803688                6              0  0.0000
ratsit.se            24893218               37              7  0.1892
svenskafans.com      14006950                9              3  0.3333
synonymer.se         24893259               77              3  0.0390
tasteline.com        20941324                2              0  0.0000
tradera.com          25414940               39              0  0.0000
                     25414941                9              0  0.0000
                     25415005             1591            165  0.1037
                     25415006             1384             39  0.0282
                     25415008               46              0  0.0000
                     25415009               45              0  0.0000

                               ratio_percent
hostname             pid
allas.se             27190878           0.00
                     27190909           0.00
elevspel.se          24893322           0.00
                     24893323           0.00
eliteprospects.com   14006303           0.00
elle.se              27191265           0.00
                     27191267           0.00
                     27208167           0.00
eniro.se             26447955          33.33
                     26447956          33.33
                     26448029           0.00
                     26448041          50.00
                     26448062          12.50
                     26448063           0.00
everysport.com       14006888           0.00
feber.se             18805247           0.00
                     18805253           0.00
                     18805260           0.00
                     18805261           0.00
                     18805264           0.00
                     18805300           0.00
                     18805311           0.00
femina.se            27208168           0.00
fotbolldirekt.se     14006827         100.00
                     18911735           0.00
gp.se                19402974           0.00
gulesider.no         24984881           0.00
hant.se              27191378           0.00
                     27191384           0.00
hockeyallsvenskan.se 17556315           0.00
kokaihop.se          24893273           0.00
                     24893274           0.00
land.se              24984948           0.00
                     24985284           0.00
mabra.com            27191428           0.00
                     27191431           0.00
merinfo.se           24893255          21.88
                     24893256          50.00
                     24893357          23.53
                     24893358           8.70
mingolf.golf.se      19589657           0.00
mrkoll.se            18803686          50.00
                     18803688           0.00
ratsit.se            24893218          18.92
svenskafans.com      14006950          33.33
synonymer.se         24893259           3.90
tasteline.com        20941324           0.00
tradera.com          25414940           0.00
                     25414941           0.00
                     25415005          10.37
                     25415006           2.82
                     25415008           0.00
                     25415009           0.00

In [177]:
# grouped_df.reset_index().to_csv('tele2_report_2022.csv', index=False)

In [178]:
# get number of impressions for common placement IDs from tele2 data
# tele2_grouped_df = df_client_tele2.groupby(['hostname', 'placement_id'])['brand'].agg('count').reset_index()
# tele2_grouped_df.rename(columns={"brand": "num_impressions"}, inplace=True)
# tele2_grouped_df

# groupby and aggregate
tele2_grouped_df = df_client_tele2.groupby(['hostname', 'placement_id']).apply(
    lambda x: pd.Series(
        {
            'num_impressions' : x['is_imp'].count(),
            'num_inview': x.loc[x['is_iab_inview'] == 1, 'is_imp'].count()
        }
    )
).reset_index()
tele2_grouped_df

                           hostname  placement_id  num_impressions  num_inview
0                alingsastidning.se      26502313                1           0
1                          allas.se      27190836                8           5
2                          allas.se      27190878               32          23
3                          allas.se      27190909               10           8
4                          allas.se      27192191               10          10
..                              ...           ...              ...         ...
288                   vitahasten.se      17557143               14           6
289                   vitahasten.se      17557162               18          14
290                   vitahasten.se      17557163                9           6
291  webcache.googleusercontent.com      24893259                6           4
292  webcache.googleusercontent.com      24893360                3           1

[293 rows x 4 columns]

In [179]:
tele2_grouped_df[tele2_grouped_df['num_impressions'] != tele2_grouped_df['num_inview']]

                           hostname  placement_id  num_impressions  num_inview
0                alingsastidning.se      26502313                1           0
1                          allas.se      27190836                8           5
2                          allas.se      27190878               32          23
3                          allas.se      27190909               10           8
6                          allas.se      27192271                8           6
..                              ...           ...              ...         ...
288                   vitahasten.se      17557143               14           6
289                   vitahasten.se      17557162               18          14
290                   vitahasten.se      17557163                9           6
291  webcache.googleusercontent.com      24893259                6           4
292  webcache.googleusercontent.com      24893360                3           1

[261 rows x 4 columns]

In [180]:
def get_sample_size(num_impressions):
    if num_impressions <= 5:
        return "low"
    elif num_impressions > 5 and num_impressions <= 10:
        return "medium"
    else:
        return "high"

# merge grouped_df with tele2_grouped_df to have number of impressions from tele2 input data
new_df = pd.merge(grouped_df, tele2_grouped_df,  how='left', left_on=['hostname','pid'], right_on = ['hostname','placement_id'])
new_df.rename(columns={"num_impressions_y": "tele2_impressions"}, inplace=True)
new_df['tele2_fixations'] = round(new_df['tele2_impressions'] * new_df['ratio'])
# recalculate ratio and ratio_percent, to be exact value from their data
new_df['ratio'] = round(new_df['tele2_fixations'] / new_df['tele2_impressions'], 4)
new_df['ratio_percent'] = round(new_df['ratio'] * 100, 2)
new_df['sample_size'] = new_df['num_impressions_x'].apply(lambda num_impressions: get_sample_size(num_impressions))

In [181]:
new_df

,hostname,num_impressions_x,num_fixations,ratio,ratio_percent,placement_id,tele2_impressions,num_inview,tele2_fixations,sample_size
0,allas.se,1,0,0.0000,0.00,27190878.0,32.0,23.0,0.0,low
1,allas.se,3,0,0.0000,0.00,27190909.0,10.0,8.0,0.0,low
2,elevspel.se,5,0,0.0000,0.00,24893322.0,8838.0,4598.0,0.0,low
3,elevspel.se,3,0,0.0000,0.00,24893323.0,794.0,123.0,0.0,low
4,eliteprospects.com,1,0,0.0000,0.00,14006303.0,2936.0,2267.0,0.0,low
5,elle.se,1,0,0.0000,0.00,27191265.0,22.0,10.0,0.0,low
6,elle.se,4,0,0.0000,0.00,27191267.0,23.0,9.0,0.0,low
7,elle.se,3,0,0.0000,0.00,27208167.0,60.0,43.0,0.0,low
8,eniro.se,6,2,0.3297,32.97,26447955.0,91.0,70.0,30.0,medium
9,eniro.se,6,2,0.3317,33.17,26447956.0,205.0,87.0,68.0,medium
10,eniro.se,7,0,0.0000,0.00,26448029.0,165.0,63.0,0.0,medium
11,eniro.se,2,1,0.5000,50.00,26448041.0,756.0,701.0,378.0,low
12,eniro.se,16,2,0.1242,12.42,26448062.0,499.0,392.0,62.0,high
13,eniro.se,4,0,0.0000,0.00,26448063.0,1160.0,551.0,0.0,low
14,everysport.com,1,0,0.0000,0.00,14006888.0,469.0,280.0,0.0,low
15,feber.se,3,0,0.0000,0.00,18805247.0,3.0,2.0,0.0,low
16,feber.se,3,0,0.0000,0.00,18805253.0,4.0,3.0,0.0,low
17,feber.se,4,0,0.0000,0.00,18805260.0,4.0,2.0,0.0,low
18,feber.se,5,0,0.0000,0.00,18805261.0,6.0,3.0,0.0,low
19,feber.se,2,0,0.0000,0.00,18805264.0,6.0,3.0,0.0,low
20,feber.se,3,0,0.0000,0.00,18805300.0,3.0,1.0,0.0,low
21,feber.se,2,0,0.0000,0.00,18805311.0,3.0,2.0,0.0,low
22,femina.se,1,0,0.0000,0.00,27208168.0,2.0,1.0,0.0,low
23,fotbolldirekt.se,1,1,1.0000,100.00,14006827.0,519.0,317.0,519.0,low
24,fotbolldirekt.se,1,0,0.0000,0.00,18911735.0,2079.0,1512.0,0.0,low
25,gp.se,4,0,0.0000,0.00,19402974.0,9.0,6.0,0.0,low
26,gulesider.no,1,0,0.0000,0.00,24984881.0,86.0,73.0,0.0,low
27,hant.se,1,0,0.0000,0.00,27191378.0,57.0,44.0,0.0,low
28,hant.se,9,0,0.0000,0.00,27191384.0,32.0,11.0,0.0,medium
29,hockeyallsvenskan.se,2,0,0.0000,0.00,17556315.0,520.0,352.0,0.0,low
30,kokaihop.se,1,0,0.0000,0.00,24893273.0,430.0,70.0,0.0,low
31,kokaihop.se,9,0,0.0000,0.00,24893274.0,1407.0,742.0,0.0,medium
32,land.se,6,0,0.0000,0.00,24984948.0,41.0,11.0,0.0,medium
33,land.se,1,0,0.0000,0.00,24985284.0,23.0,11.0,0.0,low
34,mabra.com,1,0,0.0000,0.00,27191428.0,2.0,2.0,0.0,low
35,mabra.com,1,0,0.0000,0.00,27191431.0,13.0,5.0,0.0,low
36,merinfo.se,32,7,0.2222,22.22,24893255.0,9.0,7.0,2.0,high
37,merinfo.se,6,3,0.4989,49.89,24893256.0,473.0,141.0,236.0,medium
38,merinfo.se,34,8,0.2143,21.43,24893357.0,14.0,6.0,3.0,high
39,merinfo.se,46,4,0.0750,7.50,24893358.0,40.0,9.0,3.0,high
40,mingolf.golf.se,3,0,NaN,NaN,NaN,NaN,NaN,NaN,low
41,mrkoll.se,32,16,0.5070,50.70,18803686.0,71.0,61.0,36.0,high
42,mrkoll.se,6,0,0.0000,0.00,18803688.0,55.0,34.0,0.0,medium
43,ratsit.se,37,7,0.1892,18.92,24893218.0,14962.0,6723.0,2831.0,high
44,svenskafans.com,9,3,0.3341,33.41,14006950.0,437.0,257.0,146.0,medium
45,synonymer.se,77,3,0.0392,3.92,24893259.0,2170.0,1076.0,85.0,high
46,tasteline.com,2,0,0.0000,0.00,20941324.0,25.0,19.0,0.0,low
47,tradera.com,39,0,0.0000,0.00,25414940.0,7674.0,5166.0,0.0,high
48,tradera.com,9,0,0.0000,0.00,25414941.0,6854.0,4436.0,0.0,medium
49,tradera.com,1591,165,0.1037,10.37,25415005.0,15426.0,8802.0,1600.0,high
50,tradera.com,1384,39,0.0282,2.82,25415006.0,15372.0,8940.0,433.0,high
51,tradera.com,46,0,0.0000,0.00,25415008.0,9170.0,5812.0,0.0,high
52,tradera.com,45,0,0.0000,0.00,25415009.0,10039.0,6715.0,0.0,high

In [182]:
result_df = new_df[['hostname', 'placement_id', 'tele2_impressions', 'num_inview', 'tele2_fixations', 'ratio', 'ratio_percent', 'sample_size']]
result_df.rename(columns={'tele2_impressions': 'num_impressions', 'tele2_fixations': 'num_fixations'}, inplace=True)
result_df

/home/markopejic/clear/lib/python3.7/site-packages/pandas/core/frame.py:5042: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,hostname,placement_id,num_impressions,num_inview,num_fixations,ratio,ratio_percent,sample_size
0,allas.se,27190878.0,32.0,23.0,0.0,0.0000,0.00,low
1,allas.se,27190909.0,10.0,8.0,0.0,0.0000,0.00,low
2,elevspel.se,24893322.0,8838.0,4598.0,0.0,0.0000,0.00,low
3,elevspel.se,24893323.0,794.0,123.0,0.0,0.0000,0.00,low
4,eliteprospects.com,14006303.0,2936.0,2267.0,0.0,0.0000,0.00,low
5,elle.se,27191265.0,22.0,10.0,0.0,0.0000,0.00,low
6,elle.se,27191267.0,23.0,9.0,0.0,0.0000,0.00,low
7,elle.se,27208167.0,60.0,43.0,0.0,0.0000,0.00,low
8,eniro.se,26447955.0,91.0,70.0,30.0,0.3297,32.97,medium
9,eniro.se,26447956.0,205.0,87.0,68.0,0.3317,33.17,medium
10,eniro.se,26448029.0,165.0,63.0,0.0,0.0000,0.00,medium
11,eniro.se,26448041.0,756.0,701.0,378.0,0.5000,50.00,low
12,eniro.se,26448062.0,499.0,392.0,62.0,0.1242,12.42,high
13,eniro.se,26448063.0,1160.0,551.0,0.0,0.0000,0.00,low
14,everysport.com,14006888.0,469.0,280.0,0.0,0.0000,0.00,low
15,feber.se,18805247.0,3.0,2.0,0.0,0.0000,0.00,low
16,feber.se,18805253.0,4.0,3.0,0.0,0.0000,0.00,low
17,feber.se,18805260.0,4.0,2.0,0.0,0.0000,0.00,low
18,feber.se,18805261.0,6.0,3.0,0.0,0.0000,0.00,low
19,feber.se,18805264.0,6.0,3.0,0.0,0.0000,0.00,low
20,feber.se,18805300.0,3.0,1.0,0.0,0.0000,0.00,low
21,feber.se,18805311.0,3.0,2.0,0.0,0.0000,0.00,low
22,femina.se,27208168.0,2.0,1.0,0.0,0.0000,0.00,low
23,fotbolldirekt.se,14006827.0,519.0,317.0,519.0,1.0000,100.00,low
24,fotbolldirekt.se,18911735.0,2079.0,1512.0,0.0,0.0000,0.00,low
25,gp.se,19402974.0,9.0,6.0,0.0,0.0000,0.00,low
26,gulesider.no,24984881.0,86.0,73.0,0.0,0.0000,0.00,low
27,hant.se,27191378.0,57.0,44.0,0.0,0.0000,0.00,low
28,hant.se,27191384.0,32.0,11.0,0.0,0.0000,0.00,medium
29,hockeyallsvenskan.se,17556315.0,520.0,352.0,0.0,0.0000,0.00,low
30,kokaihop.se,24893273.0,430.0,70.0,0.0,0.0000,0.00,low
31,kokaihop.se,24893274.0,1407.0,742.0,0.0,0.0000,0.00,medium
32,land.se,24984948.0,41.0,11.0,0.0,0.0000,0.00,medium
33,land.se,24985284.0,23.0,11.0,0.0,0.0000,0.00,low
34,mabra.com,27191428.0,2.0,2.0,0.0,0.0000,0.00,low
35,mabra.com,27191431.0,13.0,5.0,0.0,0.0000,0.00,low
36,merinfo.se,24893255.0,9.0,7.0,2.0,0.2222,22.22,high
37,merinfo.se,24893256.0,473.0,141.0,236.0,0.4989,49.89,medium
38,merinfo.se,24893357.0,14.0,6.0,3.0,0.2143,21.43,high
39,merinfo.se,24893358.0,40.0,9.0,3.0,0.0750,7.50,high
40,mingolf.golf.se,NaN,NaN,NaN,NaN,NaN,NaN,low
41,mrkoll.se,18803686.0,71.0,61.0,36.0,0.5070,50.70,high
42,mrkoll.se,18803688.0,55.0,34.0,0.0,0.0000,0.00,medium
43,ratsit.se,24893218.0,14962.0,6723.0,2831.0,0.1892,18.92,high
44,svenskafans.com,14006950.0,437.0,257.0,146.0,0.3341,33.41,medium
45,synonymer.se,24893259.0,2170.0,1076.0,85.0,0.0392,3.92,high
46,tasteline.com,20941324.0,25.0,19.0,0.0,0.0000,0.00,low
47,tradera.com,25414940.0,7674.0,5166.0,0.0,0.0000,0.00,high
48,tradera.com,25414941.0,6854.0,4436.0,0.0,0.0000,0.00,medium
49,tradera.com,25415005.0,15426.0,8802.0,1600.0,0.1037,10.37,high
50,tradera.com,25415006.0,15372.0,8940.0,433.0,0.0282,2.82,high
51,tradera.com,25415008.0,9170.0,5812.0,0.0,0.0000,0.00,high
52,tradera.com,25415009.0,10039.0,6715.0,0.0,0.0000,0.00,high

In [183]:
result_df.to_csv(f'tele2_{campaign}_2022.csv', index=False)