In [1]:
import pandas as pd
import numpy as np

In [2]:
client = "firstvet"
df = pd.read_excel(f"./{client}_results.xlsx")
df

,hostname,Impressions,Inviews,Fixations,Fixation/Inview Ratio,Average Fixation Duration,Total Fixation Duration,Sample Size
0,aftonbladet.se,1316998,936296,344320,36.77,4034,1388986880,medium
1,bloggar.aftonbladet.se,120249,77453,60737,78.42,3929,238635673,low
2,klart.se,3805,2384,1393,58.43,1902,2649486,low
3,malservice.aftonbladet.se,3,2,1,50.00,654,654,low
4,skonhetsredaktorerna.se,30623,19803,30623,154.64,1770,54202710,low
5,svd.se,28158,20906,9759,46.68,8452,82483068,medium
6,tramsfrans.aftonbladet.se,30623,19803,0,0.00,0,0,low
7,tv.nu,28407,18505,6198,33.49,2273,14088054,medium

In [3]:
df = df[df["Sample Size"].isin(["high", "medium"])]
df["group"] = 1

/tmp/ipykernel_17448/497368128.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["group"] = 1

In [4]:
final_df = df.groupby(["group"]).apply(
    lambda x: pd.Series(
        {
            "Impressions": np.floor(np.average(x["Impressions"], weights=x["Impressions"])),
            "Inviews": np.floor(np.average(x["Inviews"], weights=x["Inviews"])),
            "Fixations": np.floor(np.average(x["Fixations"], weights=x["Fixations"])),
            "Fixation/Inview Ratio": round(np.average(x["Fixation/Inview Ratio"], weights=x["Impressions"]), 2),
            "Average Fixation Duration": np.floor(np.average(x["Average Fixation Duration"], weights=x["Fixations"])),
            "Total Fixation Duration": np.floor(np.average(x["Average Fixation Duration"], weights=x["Fixations"]) *  np.floor(np.average(x["Fixations"], weights=x["Fixations"])))
        }
    )
)
final_df = final_df.reset_index()
final_df

,group,Impressions,Inviews,Fixations,Fixation/Inview Ratio,Average Fixation Duration,Total Fixation Duration
0,1,1263927.0,899275.0,329440.0,36.91,4123.0,1.358405e+09

In [5]:
final_df = final_df[["Impressions", "Inviews", "Fixations", "Fixation/Inview Ratio", "Average Fixation Duration", "Total Fixation Duration"]]

final_df.to_excel(f"./{client}_results_consolidated.xlsx", index=False)